/**
 * Seed data standing in for the Laravel backend.
 *
 * Shapes mirror what the real API is expected to return, so swapping this for
 * HTTP calls should not ripple past the api/ module.
 *
 * Customer names intentionally overlap with the issue seed data — Acme Corp,
 * Northwind Trading, etc. — so cross-feature references look realistic.
 */

export const MOCK_CUSTOMERS = [
  {
    id: 1,
    name: 'Acme Corp',
    email: 'support@acmecorp.com',
    phone: '+1 (415) 555-0100',
    company: 'Acme Corp',
    industry: 'Technology',
    status: 'active',
    issueCount: 4,
    contactName: 'Priya Kumar',
    notes: 'Enterprise client since 2024. Primary contact for all issue escalations.',
    createdAt: '2024-03-15T09:00:00Z',
    updatedAt: '2026-08-12T09:05:00Z',
  },
  {
    id: 2,
    name: 'Northwind Trading',
    email: 'hello@northwind.io',
    phone: '+44 20 7946 0200',
    company: 'Northwind Trading Ltd',
    industry: 'Logistics',
    status: 'active',
    issueCount: 3,
    contactName: 'Marcus Webb',
    notes: 'UK-based trading company. Requires GDPR-compliant handling.',
    createdAt: '2024-05-22T14:30:00Z',
    updatedAt: '2026-08-11T08:00:00Z',
  },
  {
    id: 3,
    name: 'Vertex Labs',
    email: 'ops@vertexlabs.dev',
    phone: '+1 (650) 555-0300',
    company: 'Vertex Labs Inc',
    industry: 'Software',
    status: 'active',
    issueCount: 3,
    contactName: 'Internal Team',
    notes: 'Internal product team. Uses the CRM for dogfooding.',
    createdAt: '2024-01-10T08:00:00Z',
    updatedAt: '2026-08-11T15:40:00Z',
  },
  {
    id: 4,
    name: 'Bluepeak Retail',
    email: 'support@bluepeak.co',
    phone: '+1 (212) 555-0400',
    company: 'Bluepeak Retail Group',
    industry: 'Retail',
    status: 'active',
    issueCount: 2,
    contactName: 'Lena Ortiz',
    notes: 'Mid-market retail chain. Seasonal spike in support requests.',
    createdAt: '2024-06-18T11:00:00Z',
    updatedAt: '2026-08-06T13:15:00Z',
  },
  {
    id: 5,
    name: 'Orbit Logistics',
    email: 'tech@orbitlog.com',
    phone: '+61 2 9876 5432',
    company: 'Orbit Logistics Pty Ltd',
    industry: 'Logistics',
    status: 'active',
    issueCount: 3,
    contactName: 'Tomas Reid',
    notes: 'Australian logistics firm. Timezone offset needs attention.',
    createdAt: '2024-04-03T07:55:00Z',
    updatedAt: '2026-08-12T05:30:00Z',
  },
  {
    id: 6,
    name: 'Cascade Finance',
    email: 'it@cascadefinance.com',
    phone: '+1 (312) 555-0600',
    company: 'Cascade Financial Services',
    industry: 'Finance',
    status: 'active',
    issueCount: 1,
    contactName: 'Raj Patel',
    notes: 'Regulated industry — requires SOC 2 compliance documentation.',
    createdAt: '2024-07-20T10:30:00Z',
    updatedAt: '2026-07-15T14:20:00Z',
  },
  {
    id: 7,
    name: 'Greenfield Agri',
    email: 'admin@greenfieldagri.co',
    phone: '+27 11 555 0700',
    company: 'Greenfield Agricultural Solutions',
    industry: 'Agriculture',
    status: 'active',
    issueCount: 0,
    contactName: 'Sipho Ndlovu',
    notes: 'South African agricultural client. Low bandwidth environment.',
    createdAt: '2024-09-05T13:00:00Z',
    updatedAt: '2026-06-22T09:45:00Z',
  },
  {
    id: 8,
    name: 'Medicore Health',
    email: 'support@medicore.health',
    phone: '+49 30 555 0800',
    company: 'Medicore Health GmbH',
    industry: 'Healthcare',
    status: 'active',
    issueCount: 2,
    contactName: 'Dr. Elena Fischer',
    notes: 'German healthcare provider. HIPAA-equivalent data handling required.',
    createdAt: '2024-08-12T09:15:00Z',
    updatedAt: '2026-07-28T16:30:00Z',
  },
  {
    id: 9,
    name: 'Stratos Airlines',
    email: 'tech@stratosair.com',
    phone: '+971 4 555 0900',
    company: 'Stratos Airlines LLC',
    industry: 'Aviation',
    status: 'inactive',
    issueCount: 1,
    contactName: 'Fatima Al-Rashid',
    notes: 'Contract paused while they evaluate competitors. Revisit Q4.',
    createdAt: '2024-02-28T15:45:00Z',
    updatedAt: '2026-05-10T11:00:00Z',
  },
  {
    id: 10,
    name: 'Pixel Creative',
    email: 'hello@pixelcreative.studio',
    phone: '+1 (503) 555-1000',
    company: 'Pixel Creative Studio',
    industry: 'Media',
    status: 'active',
    issueCount: 0,
    contactName: 'Jordan Liu',
    notes: 'Creative agency. Heavy API integration usage.',
    createdAt: '2025-01-14T08:30:00Z',
    updatedAt: '2026-08-01T10:15:00Z',
  },
  {
    id: 11,
    name: 'TerraForge Mining',
    email: 'ops@terraforge.com.au',
    phone: '+61 8 9555 1100',
    company: 'TerraForge Mining Corp',
    industry: 'Mining',
    status: 'inactive',
    issueCount: 0,
    contactName: 'Bruce Callahan',
    notes: 'Churned — migrated to a competitor in Q1 2026.',
    createdAt: '2024-11-02T06:00:00Z',
    updatedAt: '2026-03-18T12:45:00Z',
  },
  {
    id: 12,
    name: 'Bright Education',
    email: 'admin@brightedu.org',
    phone: '+44 113 555 1200',
    company: 'Bright Education Trust',
    industry: 'Education',
    status: 'active',
    issueCount: 1,
    contactName: 'Sarah Jennings',
    notes: 'Non-profit education trust. Discounted pricing tier.',
    createdAt: '2025-02-10T10:00:00Z',
    updatedAt: '2026-07-20T08:30:00Z',
  },
  {
    id: 13,
    name: 'Nova Dynamics',
    email: 'engineering@novadyn.io',
    phone: '+1 (408) 555-1300',
    company: 'Nova Dynamics Inc',
    industry: 'Engineering',
    status: 'active',
    issueCount: 2,
    contactName: 'Carlos Mendes',
    notes: 'Silicon Valley engineering firm. High API throughput.',
    createdAt: '2025-03-25T14:15:00Z',
    updatedAt: '2026-08-05T17:00:00Z',
  },
  {
    id: 14,
    name: 'Coastal Realty',
    email: 'info@coastalrealty.com',
    phone: '+1 (305) 555-1400',
    company: 'Coastal Realty Group',
    industry: 'Real Estate',
    status: 'active',
    issueCount: 0,
    contactName: 'Maria Santos',
    notes: 'Florida-based real estate group. Recently onboarded.',
    createdAt: '2025-06-08T09:00:00Z',
    updatedAt: '2026-08-10T11:20:00Z',
  },
  {
    id: 15,
    name: 'Frostbyte Games',
    email: 'dev@frostbyte.gg',
    phone: '+46 8 555 1500',
    company: 'Frostbyte Interactive AB',
    industry: 'Gaming',
    status: 'active',
    issueCount: 1,
    contactName: 'Erik Lindqvist',
    notes: 'Swedish game studio. Needs webhook reliability for real-time events.',
    createdAt: '2025-04-17T12:30:00Z',
    updatedAt: '2026-08-09T14:10:00Z',
  },
]
