/**
 * Seed data standing in for the Laravel backend.
 *
 * Shapes mirror what the real API is expected to return, so swapping this for
 * HTTP calls should not ripple past the api/ module.
 */

const DEVS = {
  nadia: { name: 'Nadia Perera', initials: 'NP' },
  dilan: { name: 'Dilan Silva', initials: 'DS' },
  amara: { name: 'Amara Jayawardena', initials: 'AJ' },
  kasun: { name: 'Kasun Fernando', initials: 'KF' },
  ishara: { name: 'Ishara Wickrama', initials: 'IW' },
}

export const ASSIGNEES = DEVS

export const MOCK_ISSUES = [
  {
    id: 'SYN-1042',
    title: 'Login fails on Safari 17 after successful auth',
    description:
      'Users on Safari 17 are redirected back to the login page despite the authentication request returning 200. Suspected cookie SameSite handling.',
    status: 'open',
    priority: 'critical',
    assignee: DEVS.nadia,
    reporter: { name: 'Priya Kumar', email: 'priya@acmecorp.com' },
    customer: 'Acme Corp',
    createdAt: '2026-08-12T07:20:00Z',
    updatedAt: '2026-08-12T09:05:00Z',
  },
  {
    id: 'SYN-1041',
    title: 'CSV export times out for accounts over 10k rows',
    description:
      'Export requests exceed the 30s gateway timeout. Needs chunked streaming or a background job with email delivery.',
    status: 'in_progress',
    priority: 'high',
    assignee: DEVS.dilan,
    reporter: { name: 'Marcus Webb', email: 'marcus@northwind.io' },
    customer: 'Northwind Trading',
    createdAt: '2026-08-11T13:45:00Z',
    updatedAt: '2026-08-12T06:10:00Z',
  },
  {
    id: 'SYN-1040',
    title: 'Duplicate notification emails on status change',
    description:
      'Two identical emails are dispatched when an issue moves to Resolved. Likely a double-bound event listener.',
    status: 'open',
    priority: 'medium',
    assignee: null,
    reporter: { name: 'Priya Kumar', email: 'priya@acmecorp.com' },
    customer: 'Acme Corp',
    createdAt: '2026-08-10T10:30:00Z',
    updatedAt: '2026-08-10T10:30:00Z',
  },
  {
    id: 'SYN-1039',
    title: 'Add bulk assign action to issue list',
    description:
      'Support selecting multiple issues and assigning them to a developer in one action.',
    status: 'in_progress',
    priority: 'low',
    assignee: DEVS.amara,
    reporter: { name: 'Internal', email: 'team@synnex.com' },
    customer: 'Vertex Labs',
    createdAt: '2026-08-09T08:15:00Z',
    updatedAt: '2026-08-11T15:40:00Z',
  },
  {
    id: 'SYN-1038',
    title: 'Avatar upload crops incorrectly on portrait images',
    description:
      'Portrait images are centre-cropped from the top, cutting off faces. Should crop around the detected subject.',
    status: 'resolved',
    priority: 'low',
    assignee: DEVS.kasun,
    reporter: { name: 'Lena Ortiz', email: 'lena@bluepeak.co' },
    customer: 'Bluepeak Retail',
    createdAt: '2026-08-05T11:00:00Z',
    updatedAt: '2026-08-08T09:25:00Z',
  },
  {
    id: 'SYN-1037',
    title: 'Dashboard totals disagree with report export',
    description:
      'Open issue count on the dashboard excludes issues in triage, while the export includes them.',
    status: 'open',
    priority: 'high',
    assignee: DEVS.ishara,
    reporter: { name: 'Marcus Webb', email: 'marcus@northwind.io' },
    customer: 'Northwind Trading',
    createdAt: '2026-08-08T14:50:00Z',
    updatedAt: '2026-08-11T08:00:00Z',
  },
  {
    id: 'SYN-1036',
    title: 'Session expires without warning during form entry',
    description:
      'Long forms lose all input when the session times out. Needs a warning modal and draft persistence.',
    status: 'in_progress',
    priority: 'critical',
    assignee: DEVS.nadia,
    reporter: { name: 'Tomas Reid', email: 'tomas@orbitlog.com' },
    customer: 'Orbit Logistics',
    createdAt: '2026-08-07T16:20:00Z',
    updatedAt: '2026-08-12T05:30:00Z',
  },
  {
    id: 'SYN-1035',
    title: 'Search returns archived customers',
    description:
      'Archived records appear in the global search dropdown with no visual distinction.',
    status: 'resolved',
    priority: 'medium',
    assignee: DEVS.dilan,
    reporter: { name: 'Lena Ortiz', email: 'lena@bluepeak.co' },
    customer: 'Bluepeak Retail',
    createdAt: '2026-08-02T09:10:00Z',
    updatedAt: '2026-08-06T13:15:00Z',
  },
  {
    id: 'SYN-1034',
    title: 'Timezone offset wrong in activity log',
    description:
      'Timestamps render in UTC rather than the viewing user’s local timezone.',
    status: 'open',
    priority: 'medium',
    assignee: null,
    reporter: { name: 'Tomas Reid', email: 'tomas@orbitlog.com' },
    customer: 'Orbit Logistics',
    createdAt: '2026-08-06T12:00:00Z',
    updatedAt: '2026-08-06T12:00:00Z',
  },
  {
    id: 'SYN-1033',
    title: 'PDF invoice missing tax breakdown',
    description:
      'Generated invoices show only the gross total. Regulatory requirement to itemise tax.',
    status: 'closed',
    priority: 'high',
    assignee: DEVS.amara,
    reporter: { name: 'Priya Kumar', email: 'priya@acmecorp.com' },
    customer: 'Acme Corp',
    createdAt: '2026-07-28T10:45:00Z',
    updatedAt: '2026-08-04T16:00:00Z',
  },
  {
    id: 'SYN-1032',
    title: 'Slow query on customer detail page',
    description:
      'Page takes 4-6s to load for customers with more than 500 linked issues. Missing index on issues.customer_id.',
    status: 'in_progress',
    priority: 'high',
    assignee: DEVS.kasun,
    reporter: { name: 'Internal', email: 'team@synnex.com' },
    customer: 'Vertex Labs',
    createdAt: '2026-07-30T08:30:00Z',
    updatedAt: '2026-08-11T11:20:00Z',
  },
  {
    id: 'SYN-1031',
    title: 'Cannot remove last admin from workspace',
    description:
      'The guard blocking removal of the final admin also fires when transferring ownership.',
    status: 'open',
    priority: 'medium',
    assignee: DEVS.ishara,
    reporter: { name: 'Marcus Webb', email: 'marcus@northwind.io' },
    customer: 'Northwind Trading',
    createdAt: '2026-07-29T15:05:00Z',
    updatedAt: '2026-08-03T09:45:00Z',
  },
  {
    id: 'SYN-1030',
    title: 'Webhook retries stop after first failure',
    description:
      'Exponential backoff is configured but the retry queue drops the job after a single 500 response.',
    status: 'open',
    priority: 'critical',
    assignee: DEVS.dilan,
    reporter: { name: 'Tomas Reid', email: 'tomas@orbitlog.com' },
    customer: 'Orbit Logistics',
    createdAt: '2026-07-27T07:55:00Z',
    updatedAt: '2026-08-09T14:10:00Z',
  },
  {
    id: 'SYN-1029',
    title: 'Sorting by priority ignores custom order',
    description:
      'Priority column sorts alphabetically instead of by severity rank.',
    status: 'resolved',
    priority: 'low',
    assignee: DEVS.nadia,
    reporter: { name: 'Internal', email: 'team@synnex.com' },
    customer: 'Vertex Labs',
    createdAt: '2026-07-25T13:20:00Z',
    updatedAt: '2026-07-31T10:05:00Z',
  },
  {
    id: 'SYN-1028',
    title: 'Mobile drawer traps scroll on iOS',
    description:
      'Body scroll lock does not release after the navigation drawer closes on iOS Safari.',
    status: 'closed',
    priority: 'medium',
    assignee: DEVS.amara,
    reporter: { name: 'Lena Ortiz', email: 'lena@bluepeak.co' },
    customer: 'Bluepeak Retail',
    createdAt: '2026-07-22T09:40:00Z',
    updatedAt: '2026-07-30T12:35:00Z',
  },
  {
    id: 'SYN-1027',
    title: 'Attachment upload fails over 25MB silently',
    description:
      'Uploads exceeding the limit fail with no error surfaced — the progress bar simply resets.',
    status: 'open',
    priority: 'high',
    assignee: null,
    reporter: { name: 'Priya Kumar', email: 'priya@acmecorp.com' },
    customer: 'Acme Corp',
    createdAt: '2026-07-21T11:15:00Z',
    updatedAt: '2026-08-02T08:50:00Z',
  },
  {
    id: 'SYN-1026',
    title: 'Keyboard shortcut conflicts with browser find',
    description:
      'Ctrl+F is intercepted by the in-app search, breaking the native find dialog.',
    status: 'open',
    priority: 'low',
    assignee: DEVS.kasun,
    reporter: { name: 'Internal', email: 'team@synnex.com' },
    customer: 'Vertex Labs',
    createdAt: '2026-07-19T16:00:00Z',
    updatedAt: '2026-07-26T09:30:00Z',
  },
  {
    id: 'SYN-1025',
    title: 'Customer merge loses linked issues',
    description:
      'Merging two customer records reassigns contacts but orphans their issue history.',
    status: 'resolved',
    priority: 'critical',
    assignee: DEVS.ishara,
    reporter: { name: 'Marcus Webb', email: 'marcus@northwind.io' },
    customer: 'Northwind Trading',
    createdAt: '2026-07-16T10:20:00Z',
    updatedAt: '2026-07-24T15:45:00Z',
  },
  {
    id: 'SYN-1024',
    title: 'Report scheduler runs twice on DST change',
    description:
      'Scheduled reports fire twice on the night clocks go back, duplicating deliveries.',
    status: 'in_progress',
    priority: 'medium',
    assignee: DEVS.dilan,
    reporter: { name: 'Tomas Reid', email: 'tomas@orbitlog.com' },
    customer: 'Orbit Logistics',
    createdAt: '2026-07-14T08:05:00Z',
    updatedAt: '2026-08-07T13:00:00Z',
  },
  {
    id: 'SYN-1023',
    title: 'Empty state shown while data still loading',
    description:
      'The "no results" panel flashes before the first response arrives.',
    status: 'closed',
    priority: 'low',
    assignee: DEVS.nadia,
    reporter: { name: 'Internal', email: 'team@synnex.com' },
    customer: 'Vertex Labs',
    createdAt: '2026-07-12T14:30:00Z',
    updatedAt: '2026-07-20T11:10:00Z',
  },
  {
    id: 'SYN-1022',
    title: 'Assignee filter resets on page refresh',
    description:
      'Filter state is held in memory only and is lost on reload or deep link.',
    status: 'open',
    priority: 'medium',
    assignee: DEVS.amara,
    reporter: { name: 'Lena Ortiz', email: 'lena@bluepeak.co' },
    customer: 'Bluepeak Retail',
    createdAt: '2026-07-09T09:00:00Z',
    updatedAt: '2026-07-18T16:20:00Z',
  },
  {
    id: 'SYN-1021',
    title: 'API rate limit not surfaced to user',
    description:
      'A 429 response renders as a generic error with no indication of when to retry.',
    status: 'open',
    priority: 'high',
    assignee: DEVS.kasun,
    reporter: { name: 'Priya Kumar', email: 'priya@acmecorp.com' },
    customer: 'Acme Corp',
    createdAt: '2026-07-06T12:45:00Z',
    updatedAt: '2026-07-29T10:00:00Z',
  },
]
