/**
 * Seed data for the mock issues API.
 *
 * Shapes and vocabulary mirror what the real API returns — statuses are
 * 'Open' | 'In Progress' | 'QA' | 'Resolved', priorities are
 * 'High' | 'Medium' | 'Low', and there is no `updatedAt`, because tickets
 * have no such column. Keeping the two in step is what lets a feature be
 * flipped between mock and http with a single env flag.
 */

const DEVS = {
  3: { id: 3, name: 'Nadia Perera', initials: 'NP' },
  4: { id: 4, name: 'Dilan Silva', initials: 'DS' },
  5: { id: 5, name: 'Amara Jayawardena', initials: 'AJ' },
  6: { id: 6, name: 'Kasun Fernando', initials: 'KF' },
  7: { id: 7, name: 'Ishara Wickrama', initials: 'IW' },
}

export const ASSIGNEES = DEVS

export const CUSTOMERS = [
  { id: 1, name: 'Acme Corp' },
  { id: 2, name: 'Northwind Trading' },
  { id: 3, name: 'Vertex Labs' },
  { id: 4, name: 'Bluepeak Retail' },
  { id: 5, name: 'Orbit Logistics' },
]

export const PRODUCTS = [
  { id: 1, name: 'POS System' },
  { id: 2, name: 'Annual Support Retainer' },
  { id: 3, name: 'Synnex ERP Enterprise' },
]

const customer = (id) => CUSTOMERS.find((entry) => entry.id === id)
const product = (id) => PRODUCTS.find((entry) => entry.id === id)

export const MOCK_ISSUES = [
  {
    id: 'SYN-1042',
    title: 'Login fails on Safari 17 after successful auth',
    description:
      'Users on Safari 17 are redirected back to the login page despite the authentication request returning 200. Suspected cookie SameSite handling.',
    status: 'Open',
    priority: 'High',
    category: 'Bug',
    customer: customer(1),
    product: product(1),
    assignee: DEVS[3],
    createdAt: '2026-08-12T07:20:00Z',
    completedAt: null,
    comments: [],
  },
  {
    id: 'SYN-1041',
    title: 'CSV export times out for accounts over 10k rows',
    description:
      'Export requests exceed the 30s gateway timeout. Needs chunked streaming or a background job with email delivery.',
    status: 'In Progress',
    priority: 'High',
    category: 'Bug',
    customer: customer(2),
    product: product(3),
    assignee: DEVS[4],
    createdAt: '2026-08-11T13:45:00Z',
    completedAt: null,
    comments: [],
  },
  {
    id: 'SYN-1040',
    title: 'Duplicate notification emails on status change',
    description:
      'Two identical emails are dispatched when an issue moves to Resolved. Likely a double-bound event listener.',
    status: 'Open',
    priority: 'Medium',
    category: 'Bug',
    customer: customer(1),
    product: product(1),
    assignee: null,
    createdAt: '2026-08-10T10:30:00Z',
    completedAt: null,
    comments: [],
  },
  {
    id: 'SYN-1039',
    title: 'Add bulk assign action to issue list',
    description:
      'Support selecting multiple issues and assigning them to a developer in one action.',
    status: 'In Progress',
    priority: 'Low',
    category: 'Feature',
    customer: customer(3),
    product: product(3),
    assignee: DEVS[5],
    createdAt: '2026-08-09T08:15:00Z',
    completedAt: null,
    comments: [],
  },
  {
    id: 'SYN-1038',
    title: 'Avatar upload crops incorrectly on portrait images',
    description:
      'Portrait images are centre-cropped from the top, cutting off faces. Should crop around the detected subject.',
    status: 'Resolved',
    priority: 'Low',
    category: 'Bug',
    customer: customer(4),
    product: product(1),
    assignee: DEVS[6],
    createdAt: '2026-08-05T11:00:00Z',
    completedAt: '2026-08-08T09:25:00Z',
    comments: [],
  },
  {
    id: 'SYN-1037',
    title: 'Dashboard totals disagree with report export',
    description:
      'Open issue count on the dashboard excludes issues in triage, while the export includes them.',
    status: 'QA',
    priority: 'High',
    category: 'Bug',
    customer: customer(2),
    product: product(3),
    assignee: DEVS[7],
    createdAt: '2026-08-08T14:50:00Z',
    completedAt: null,
    comments: [],
  },
  {
    id: 'SYN-1036',
    title: 'Session expires without warning during form entry',
    description:
      'Long forms lose all input when the session times out. Needs a warning modal and draft persistence.',
    status: 'In Progress',
    priority: 'High',
    category: 'Feature',
    customer: customer(5),
    product: product(3),
    assignee: DEVS[3],
    createdAt: '2026-08-07T16:20:00Z',
    completedAt: null,
    comments: [],
  },
  {
    id: 'SYN-1035',
    title: 'Search returns archived customers',
    description:
      'Archived records appear in the global search dropdown with no visual distinction.',
    status: 'Resolved',
    priority: 'Medium',
    category: 'Bug',
    customer: customer(4),
    product: product(1),
    assignee: DEVS[4],
    createdAt: '2026-08-02T09:10:00Z',
    completedAt: '2026-08-06T13:15:00Z',
    comments: [],
  },
  {
    id: 'SYN-1034',
    title: 'Timezone offset wrong in activity log',
    description:
      'Timestamps render in UTC rather than the viewing user’s local timezone.',
    status: 'Open',
    priority: 'Medium',
    category: 'Bug',
    customer: customer(5),
    product: product(2),
    assignee: null,
    createdAt: '2026-08-06T12:00:00Z',
    completedAt: null,
    comments: [],
  },
  {
    id: 'SYN-1033',
    title: 'PDF invoice missing tax breakdown',
    description:
      'Generated invoices show only the gross total. Regulatory requirement to itemise tax.',
    status: 'Resolved',
    priority: 'High',
    category: 'Bug',
    customer: customer(1),
    product: product(3),
    assignee: DEVS[5],
    createdAt: '2026-07-28T10:45:00Z',
    completedAt: '2026-08-04T16:00:00Z',
    comments: [],
  },
  {
    id: 'SYN-1032',
    title: 'Slow query on customer detail page',
    description:
      'Page takes 4-6s to load for customers with more than 500 linked issues. Missing index on tickets.customer_id.',
    status: 'In Progress',
    priority: 'High',
    category: 'Bug',
    customer: customer(3),
    product: product(3),
    assignee: DEVS[6],
    createdAt: '2026-07-30T08:30:00Z',
    completedAt: null,
    comments: [],
  },
  {
    id: 'SYN-1031',
    title: 'Cannot remove last admin from workspace',
    description:
      'The guard blocking removal of the final admin also fires when transferring ownership.',
    status: 'Open',
    priority: 'Medium',
    category: 'Bug',
    customer: customer(2),
    product: product(3),
    assignee: DEVS[7],
    createdAt: '2026-07-29T15:05:00Z',
    completedAt: null,
    comments: [],
  },
  {
    id: 'SYN-1030',
    title: 'Webhook retries stop after first failure',
    description:
      'Exponential backoff is configured but the retry queue drops the job after a single 500 response.',
    status: 'Open',
    priority: 'High',
    category: 'Bug',
    customer: customer(5),
    product: product(2),
    assignee: DEVS[4],
    createdAt: '2026-07-27T07:55:00Z',
    completedAt: null,
    comments: [],
  },
  {
    id: 'SYN-1029',
    title: 'Sorting by priority ignores custom order',
    description:
      'Priority column sorts alphabetically instead of by severity rank.',
    status: 'Resolved',
    priority: 'Low',
    category: 'Bug',
    customer: customer(3),
    product: product(1),
    assignee: DEVS[3],
    createdAt: '2026-07-25T13:20:00Z',
    completedAt: '2026-07-31T10:05:00Z',
    comments: [],
  },
  {
    id: 'SYN-1028',
    title: 'Mobile drawer traps scroll on iOS',
    description:
      'Body scroll lock does not release after the navigation drawer closes on iOS Safari.',
    status: 'Resolved',
    priority: 'Medium',
    category: 'Bug',
    customer: customer(4),
    product: product(1),
    assignee: DEVS[5],
    createdAt: '2026-07-22T09:40:00Z',
    completedAt: '2026-07-30T12:35:00Z',
    comments: [],
  },
  {
    id: 'SYN-1027',
    title: 'Attachment upload fails over 25MB silently',
    description:
      'Uploads exceeding the limit fail with no error surfaced — the progress bar simply resets.',
    status: 'Open',
    priority: 'High',
    category: 'Bug',
    customer: customer(1),
    product: product(3),
    assignee: null,
    createdAt: '2026-07-21T11:15:00Z',
    completedAt: null,
    comments: [],
  },
  {
    id: 'SYN-1026',
    title: 'Keyboard shortcut conflicts with browser find',
    description:
      'Ctrl+F is intercepted by the in-app search, breaking the native find dialog.',
    status: 'QA',
    priority: 'Low',
    category: 'Bug',
    customer: customer(3),
    product: product(1),
    assignee: DEVS[6],
    createdAt: '2026-07-19T16:00:00Z',
    completedAt: null,
    comments: [],
  },
  {
    id: 'SYN-1025',
    title: 'Customer merge loses linked issues',
    description:
      'Merging two customer records reassigns contacts but orphans their issue history.',
    status: 'Resolved',
    priority: 'High',
    category: 'Bug',
    customer: customer(2),
    product: product(3),
    assignee: DEVS[7],
    createdAt: '2026-07-16T10:20:00Z',
    completedAt: '2026-07-24T15:45:00Z',
    comments: [],
  },
  {
    id: 'SYN-1024',
    title: 'Report scheduler runs twice on DST change',
    description:
      'Scheduled reports fire twice on the night clocks go back, duplicating deliveries.',
    status: 'In Progress',
    priority: 'Medium',
    category: 'Bug',
    customer: customer(5),
    product: product(2),
    assignee: DEVS[4],
    createdAt: '2026-07-14T08:05:00Z',
    completedAt: null,
    comments: [],
  },
  {
    id: 'SYN-1023',
    title: 'Empty state shown while data still loading',
    description: 'The "no results" panel flashes before the first response arrives.',
    status: 'Resolved',
    priority: 'Low',
    category: 'Bug',
    customer: customer(3),
    product: product(1),
    assignee: DEVS[3],
    createdAt: '2026-07-12T14:30:00Z',
    completedAt: '2026-07-20T11:10:00Z',
    comments: [],
  },
  {
    id: 'SYN-1022',
    title: 'Assignee filter resets on page refresh',
    description:
      'Filter state is held in memory only and is lost on reload or deep link.',
    status: 'Open',
    priority: 'Medium',
    category: 'Feature',
    customer: customer(4),
    product: product(1),
    assignee: DEVS[5],
    createdAt: '2026-07-09T09:00:00Z',
    completedAt: null,
    comments: [],
  },
  {
    id: 'SYN-1021',
    title: 'API rate limit not surfaced to user',
    description:
      'A 429 response renders as a generic error with no indication of when to retry.',
    status: 'Open',
    priority: 'High',
    category: 'Bug',
    customer: customer(1),
    product: product(3),
    assignee: DEVS[6],
    createdAt: '2026-07-06T12:45:00Z',
    completedAt: null,
    comments: [],
  },
]
